name: Run docToolchain

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate HTML Documentation
        run: |
          cd ./federated-catalogue
          ./dtcw generateHTML
      
      - name: Generate PDF Documentation
        run: |
          cd ./federated-catalogue
          ./dtcw generatePDF

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: |
            federated-catalogue/build/pdf/architecture/catalogue-architecture.pdf
            federated-catalogue/build/html5/
